
#
#   make - synchronize
#

    all:directories
	cp src/pointcloud-densify-export bin/pointcloud-densify-export
	cp src/pointcloud-densify bin/pointcloud-densify

#
#   make - directories
#

    directories:
	mkdir -p bin

#
#   make - clean
#

    clean:
	rm bin/* -f
