
#
#   make - synchronize
#

    all:directories
	cp src/pointcloud-gnoproj bin/pointcloud-gnoproj
	cp src/scripts/pointcloud-gnoproj-worker bin/pointcloud-gnoproj-worker
	cp src/scripts/pointcloud-gnoproj-verify bin/pointcloud-gnoproj-verify

#
#   make - directories
#

    directories:
	mkdir -p bin

#
#   make - clean
#

    clean:
	rm bin/* -f
