
#
#   make - synchronize
#

    all:directories
	cp src/pointcloud-dependencies bin/pointcloud-dependencies
	cp src/scripts/pointcloud-dependencies-checker bin/pointcloud-dependencies-checker

#
#   make - directories
#

    directories:
	mkdir -p bin

#
#   make - clean
#

    clean:
	rm bin/* -f
