
#
#   make - synchronize
#

    all:directories
	cp src/pointcloud-openmvg-rig bin/pointcloud-openmvg-rig

#
#   make - directories
#

    directories:
	mkdir -p bin

#
#   make - clean
#

    clean:
	rm bin/* -f
