
#
#   make - synchronize
#

    all:directories
	cp src/pointcloud-merge-lr bin/pointcloud-merge-lr
	cp src/scripts/pointcloud-merge-lr-merger bin/pointcloud-merge-lr-merger

#
#   make - directories
#

    directories:
	mkdir -p bin

#
#   make - clean
#

    clean:
	rm bin/* -f
