
#
#   make - synchronize
#

    all:directories
	cp src/pointcloud-openmvg-list bin/pointcloud-openmvg-list

#
#   make - directories
#

    directories:
	mkdir -p bin

#
#   make - clean
#

    clean:
	rm bin/* -f
