
#
#   make - synchronize
#

    all:directories
	cp src/pointcloud-procedures bin/pointcloud-procedures

#
#   make - directories
#

    directories:
	mkdir -p bin

#
#   make - clean
#

    clean:
	rm bin/* -f
